# azure-pipelines.yml

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - .github/workflows/release.yml
      - CHANGELOG.md

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.3.6'
  terraformWorkDir: './examples/complete'
  terraformModulesGithubOrg: '$(Build.Repository.Name)'
steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip -OutFile terraform.zip
      Expand-Archive terraform.zip -DestinationPath $(Agent.ToolsDirectory)/terraform
      echo "##vso[task.prependpath]$(Agent.ToolsDirectory)/terraform"


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(terraformWorkDir)
      terraform init 

- script: |
    terraform fmt --check
  displayName: 'Terraform Format'

- task: CheckovPipelineTask@0
  inputs:
    directory: '.'
    quiet: true
    skipCheck: 'CKV_TF_1'

- script: |
    cd $(terraformWorkDir)
    terraform validate
  displayName: 'Terraform Validate'

- task: aquasecurity/tfsec-action@v1.0.0
  displayName: 'Run tfsec'

- script: |
    cd test
    go test -v -timeout 120m
  displayName: 'Run Terratest'

- name: Setup Infracost
  uses: infracost/actions/setup@v2
  with:
    api-key: ${{ secrets.INFRACOST_API_KEY }}

- checkout: self
  path: baseBranch
  ref: ${{ parameters.sourceBranch }}

- script: |
    infracost breakdown --path=. --format=json --out-file=/tmp/infracost-base.json
  displayName: 'Generate Infracost cost estimate baseline'

- checkout: self

- script: |
    infracost diff --path=$(terraformWorkDir) --format=json --compare-to=/tmp/infracost-base.json --out-file=/tmp/infracost.json
  displayName: 'Generate Infracost diff'

- script: |
    infracost comment github --path=/tmp/infracost.json --pull-request=$(System.PullRequest.PullRequestId) --repo=$(System.TeamProject) --github-token=$(System.AccessToken)
  condition: succeeded('Generate Infracost diff') && eq(variables['Build.Reason'], 'PullRequest')

- checkout: self

- task: hashicorp/setup-terraform@v2
  with:
    terraform_version: ${{ env.terraformVersion }}

- name: Terraform Initialize
  id: init
  run: |
    cd ${{ env.terraformWorkDir }}
    terraform init

- name: Terraform Plans
  id: plan
  continue-on-error: true
  run: |
    cd ${{ env.terraformWorkDir }}
    terraform plan -no-color -out tf.plan

- name: Upload Terraform Plan File
  if: steps.plan.outcome == 'success' && github.event_name == 'pull_request'
  uses: actions/upload-artifact@v3
  with:
    name: tf.plan
    path: ${{ env.terraformWorkDir }}/tf.plan
    retention-days: 3

- name: Terraform Show
  if: steps.plan.outcome == 'success' && (github.event_name == 'pull_request' || github.ref == 'refs/heads/main')
  id: show
  run: |-
    echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
    | sed -E 's/^([[:space:]]+)([-+])/\2\1
