trigger:
- none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cd terraform
    terraform init \
        -backend-config="resource_group_name=$(TF_VAR_AZURE_STORAGE_RESOURCE_GROUP_NAME)" \
        -backend-config="storage_account_name=$(TF_VAR_AZURE_STORAGE_ACCOUNT_NAME)" \
        -backend-config="container_name=$(TF_VAR_AZURE_STORAGE_CONTAINER_NAME)" \
        -backend-config="key=terraform.tfstate"
  displayName: 'terraform init'

- script: |
    cd terraform
    terraform validate
  displayName: 'terraform validate'

- script: |
    cd terraform
    terraform plan
  displayName: 'terraform plan'

- script: |
    cd terraform
    terraform apply -auto-approve
  env:
    TF_VAR_VM_PRIVATE_KEY: $(tfb-rsa)
  displayName: 'terraform apply'
