---
- name: Download Open JDK
  become: true
  apt:
    name: openjdk-8-jre-headless
    update_cache: yes
    state: present

- name: Validate if Java is available 
  become: true
  shell: java -version
  register: java_version_output

- name: Debug Java version output
  debug:
    msg: "{{ java_version_output.stdout }}"