- name: Install Nginx
  apt:
    name: "{{ nginx_version }}"
    update_cache: true
    state: present


- name: Delete the default Nginx configuration file
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Delete the default Nginx configuration file
  file:
    path: "/etc/nginx/sites-available/default"
    state: absent

- name: Install the Nginx configuration
  template:
    src: "templates/nginx.config.j2"
    dest: "/etc/nginx/sites-available/nginx.conf"

- name: Enable the Nginx configuration
  file:
    src: "/etc/nginx/sites-available/nginx.conf"
    dest: "/etc/nginx/sites-enabled/nginx.conf"
    state: link
  notify: Restart Nginx
